// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: perun-wallet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	protobuf "perun.network/go-perun/wire/protobuf"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestoreChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreChannelsRequest) Reset() {
	*x = RestoreChannelsRequest{}
	mi := &file_perun_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreChannelsRequest) ProtoMessage() {}

func (x *RestoreChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreChannelsRequest.ProtoReflect.Descriptor instead.
func (*RestoreChannelsRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *RestoreChannelsRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RestoreChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreChannelsResponse) Reset() {
	*x = RestoreChannelsResponse{}
	mi := &file_perun_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreChannelsResponse) ProtoMessage() {}

func (x *RestoreChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreChannelsResponse.ProtoReflect.Descriptor instead.
func (*RestoreChannelsResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *RestoreChannelsResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RestoreChannelsResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClosePerunClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosePerunClientRequest) Reset() {
	*x = ClosePerunClientRequest{}
	mi := &file_perun_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosePerunClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosePerunClientRequest) ProtoMessage() {}

func (x *ClosePerunClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosePerunClientRequest.ProtoReflect.Descriptor instead.
func (*ClosePerunClientRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *ClosePerunClientRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClosePerunClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosePerunClientResponse) Reset() {
	*x = ClosePerunClientResponse{}
	mi := &file_perun_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosePerunClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosePerunClientResponse) ProtoMessage() {}

func (x *ClosePerunClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosePerunClientResponse.ProtoReflect.Descriptor instead.
func (*ClosePerunClientResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *ClosePerunClientResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ClosePerunClientResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type NewPerunClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewPerunClientRequest) Reset() {
	*x = NewPerunClientRequest{}
	mi := &file_perun_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewPerunClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPerunClientRequest) ProtoMessage() {}

func (x *NewPerunClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPerunClientRequest.ProtoReflect.Descriptor instead.
func (*NewPerunClientRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *NewPerunClientRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type NewPerunClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewPerunClientResponse) Reset() {
	*x = NewPerunClientResponse{}
	mi := &file_perun_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewPerunClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPerunClientResponse) ProtoMessage() {}

func (x *NewPerunClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPerunClientResponse.ProtoReflect.Descriptor instead.
func (*NewPerunClientResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *NewPerunClientResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *NewPerunClientResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Generic rejected message. Returned by any endpoint on failure.
type Rejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rejected) Reset() {
	*x = Rejected{}
	mi := &file_perun_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rejected) ProtoMessage() {}

func (x *Rejected) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rejected.ProtoReflect.Descriptor instead.
func (*Rejected) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *Rejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetChannelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// L1 address of requester (serialized offchain participant)
	Requester     []byte `protobuf:"bytes,1,opt,name=requester,proto3" json:"requester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelsRequest) Reset() {
	*x = GetChannelsRequest{}
	mi := &file_perun_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelsRequest) ProtoMessage() {}

func (x *GetChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelsRequest.ProtoReflect.Descriptor instead.
func (*GetChannelsRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *GetChannelsRequest) GetRequester() []byte {
	if x != nil {
		return x.Requester
	}
	return nil
}

type GetChannelsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*GetChannelsResponse_Rejected
	//	*GetChannelsResponse_ChannelStates
	Msg           isGetChannelsResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelsResponse) Reset() {
	*x = GetChannelsResponse{}
	mi := &file_perun_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelsResponse) ProtoMessage() {}

func (x *GetChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelsResponse.ProtoReflect.Descriptor instead.
func (*GetChannelsResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *GetChannelsResponse) GetMsg() isGetChannelsResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *GetChannelsResponse) GetRejected() *Rejected {
	if x != nil {
		if x, ok := x.Msg.(*GetChannelsResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *GetChannelsResponse) GetChannelStates() *ChannelStates {
	if x != nil {
		if x, ok := x.Msg.(*GetChannelsResponse_ChannelStates); ok {
			return x.ChannelStates
		}
	}
	return nil
}

type isGetChannelsResponse_Msg interface {
	isGetChannelsResponse_Msg()
}

type GetChannelsResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type GetChannelsResponse_ChannelStates struct {
	ChannelStates *ChannelStates `protobuf:"bytes,2,opt,name=channel_states,json=channelStates,proto3,oneof"`
}

func (*GetChannelsResponse_Rejected) isGetChannelsResponse_Msg() {}

func (*GetChannelsResponse_ChannelStates) isGetChannelsResponse_Msg() {}

// for channel with state at index i, actor is at index i
type ChannelStates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []*protobuf.State      `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	ActorIdxs     []uint32               `protobuf:"varint,2,rep,packed,name=actor_idxs,json=actorIdxs,proto3" json:"actor_idxs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelStates) Reset() {
	*x = ChannelStates{}
	mi := &file_perun_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelStates) ProtoMessage() {}

func (x *ChannelStates) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelStates.ProtoReflect.Descriptor instead.
func (*ChannelStates) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *ChannelStates) GetStates() []*protobuf.State {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *ChannelStates) GetActorIdxs() []uint32 {
	if x != nil {
		return x.ActorIdxs
	}
	return nil
}

type ChannelOpenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identity of the requester.
	Requester []byte `protobuf:"bytes,1,opt,name=requester,proto3" json:"requester,omitempty"`
	// Identity of the peer to open the channel with.
	Peer []byte `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	// The desired allocation of funds within said channel.
	Allocation *protobuf.Allocation `protobuf:"bytes,3,opt,name=allocation,proto3" json:"allocation,omitempty"`
	// The duration of the challenge period.
	ChallengeDuration uint64 `protobuf:"varint,4,opt,name=challenge_duration,json=challengeDuration,proto3" json:"challenge_duration,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChannelOpenRequest) Reset() {
	*x = ChannelOpenRequest{}
	mi := &file_perun_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelOpenRequest) ProtoMessage() {}

func (x *ChannelOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelOpenRequest.ProtoReflect.Descriptor instead.
func (*ChannelOpenRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *ChannelOpenRequest) GetRequester() []byte {
	if x != nil {
		return x.Requester
	}
	return nil
}

func (x *ChannelOpenRequest) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *ChannelOpenRequest) GetAllocation() *protobuf.Allocation {
	if x != nil {
		return x.Allocation
	}
	return nil
}

func (x *ChannelOpenRequest) GetChallengeDuration() uint64 {
	if x != nil {
		return x.ChallengeDuration
	}
	return 0
}

type ChannelOpenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ChannelOpenResponse_Rejected
	//	*ChannelOpenResponse_ChannelId
	Msg           isChannelOpenResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelOpenResponse) Reset() {
	*x = ChannelOpenResponse{}
	mi := &file_perun_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelOpenResponse) ProtoMessage() {}

func (x *ChannelOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelOpenResponse.ProtoReflect.Descriptor instead.
func (*ChannelOpenResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *ChannelOpenResponse) GetMsg() isChannelOpenResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ChannelOpenResponse) GetRejected() *Rejected {
	if x != nil {
		if x, ok := x.Msg.(*ChannelOpenResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *ChannelOpenResponse) GetChannelId() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ChannelOpenResponse_ChannelId); ok {
			return x.ChannelId
		}
	}
	return nil
}

type isChannelOpenResponse_Msg interface {
	isChannelOpenResponse_Msg()
}

type ChannelOpenResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type ChannelOpenResponse_ChannelId struct {
	ChannelId []byte `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3,oneof"`
}

func (*ChannelOpenResponse_Rejected) isChannelOpenResponse_Msg() {}

func (*ChannelOpenResponse_ChannelId) isChannelOpenResponse_Msg() {}

type ChannelUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The state with which the channel should be updated.
	State         *protobuf.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelUpdateRequest) Reset() {
	*x = ChannelUpdateRequest{}
	mi := &file_perun_wallet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelUpdateRequest) ProtoMessage() {}

func (x *ChannelUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelUpdateRequest.ProtoReflect.Descriptor instead.
func (*ChannelUpdateRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *ChannelUpdateRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

type SuccessfulUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The state with which the channel was updated.
	State *protobuf.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// The channel id of the channel which was updated.
	ChannelId     []byte `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessfulUpdate) Reset() {
	*x = SuccessfulUpdate{}
	mi := &file_perun_wallet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessfulUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessfulUpdate) ProtoMessage() {}

func (x *SuccessfulUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessfulUpdate.ProtoReflect.Descriptor instead.
func (*SuccessfulUpdate) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{13}
}

func (x *SuccessfulUpdate) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *SuccessfulUpdate) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type ChannelUpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ChannelUpdateResponse_Rejected
	//	*ChannelUpdateResponse_Update
	Msg           isChannelUpdateResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelUpdateResponse) Reset() {
	*x = ChannelUpdateResponse{}
	mi := &file_perun_wallet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelUpdateResponse) ProtoMessage() {}

func (x *ChannelUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelUpdateResponse.ProtoReflect.Descriptor instead.
func (*ChannelUpdateResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{14}
}

func (x *ChannelUpdateResponse) GetMsg() isChannelUpdateResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ChannelUpdateResponse) GetRejected() *Rejected {
	if x != nil {
		if x, ok := x.Msg.(*ChannelUpdateResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *ChannelUpdateResponse) GetUpdate() *SuccessfulUpdate {
	if x != nil {
		if x, ok := x.Msg.(*ChannelUpdateResponse_Update); ok {
			return x.Update
		}
	}
	return nil
}

type isChannelUpdateResponse_Msg interface {
	isChannelUpdateResponse_Msg()
}

type ChannelUpdateResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type ChannelUpdateResponse_Update struct {
	Update *SuccessfulUpdate `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

func (*ChannelUpdateResponse_Rejected) isChannelUpdateResponse_Msg() {}

func (*ChannelUpdateResponse_Update) isChannelUpdateResponse_Msg() {}

type ChannelCloseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The channel id of the channel to be closed.
	ChannelId     []byte `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelCloseRequest) Reset() {
	*x = ChannelCloseRequest{}
	mi := &file_perun_wallet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCloseRequest) ProtoMessage() {}

func (x *ChannelCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCloseRequest.ProtoReflect.Descriptor instead.
func (*ChannelCloseRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{15}
}

func (x *ChannelCloseRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type SuccessfulClose struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The channel id of the channel which was closed.
	ChannelId     []byte `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessfulClose) Reset() {
	*x = SuccessfulClose{}
	mi := &file_perun_wallet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessfulClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessfulClose) ProtoMessage() {}

func (x *SuccessfulClose) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessfulClose.ProtoReflect.Descriptor instead.
func (*SuccessfulClose) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{16}
}

func (x *SuccessfulClose) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type ChannelCloseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ChannelCloseResponse_Rejected
	//	*ChannelCloseResponse_Close
	Msg           isChannelCloseResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelCloseResponse) Reset() {
	*x = ChannelCloseResponse{}
	mi := &file_perun_wallet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCloseResponse) ProtoMessage() {}

func (x *ChannelCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCloseResponse.ProtoReflect.Descriptor instead.
func (*ChannelCloseResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{17}
}

func (x *ChannelCloseResponse) GetMsg() isChannelCloseResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ChannelCloseResponse) GetRejected() *Rejected {
	if x != nil {
		if x, ok := x.Msg.(*ChannelCloseResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *ChannelCloseResponse) GetClose() *SuccessfulClose {
	if x != nil {
		if x, ok := x.Msg.(*ChannelCloseResponse_Close); ok {
			return x.Close
		}
	}
	return nil
}

type isChannelCloseResponse_Msg interface {
	isChannelCloseResponse_Msg()
}

type ChannelCloseResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type ChannelCloseResponse_Close struct {
	Close *SuccessfulClose `protobuf:"bytes,2,opt,name=close,proto3,oneof"`
}

func (*ChannelCloseResponse_Rejected) isChannelCloseResponse_Msg() {}

func (*ChannelCloseResponse_Close) isChannelCloseResponse_Msg() {}

// Called by the Perun channel service if it received a channel opening request
// from another peer. The proposed channel state is passed to the wallet which
// might use it to show it in to the user.
type OpenChannelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The state with which the channel should be opened.
	Proposal      *protobuf.LedgerChannelProposalMsg `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenChannelRequest) Reset() {
	*x = OpenChannelRequest{}
	mi := &file_perun_wallet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenChannelRequest) ProtoMessage() {}

func (x *OpenChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenChannelRequest.ProtoReflect.Descriptor instead.
func (*OpenChannelRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{18}
}

func (x *OpenChannelRequest) GetProposal() *protobuf.LedgerChannelProposalMsg {
	if x != nil {
		return x.Proposal
	}
	return nil
}

type OpenChannelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*OpenChannelResponse_Rejected
	//	*OpenChannelResponse_NonceShare
	Msg           isOpenChannelResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenChannelResponse) Reset() {
	*x = OpenChannelResponse{}
	mi := &file_perun_wallet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenChannelResponse) ProtoMessage() {}

func (x *OpenChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenChannelResponse.ProtoReflect.Descriptor instead.
func (*OpenChannelResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{19}
}

func (x *OpenChannelResponse) GetMsg() isOpenChannelResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *OpenChannelResponse) GetRejected() *Rejected {
	if x != nil {
		if x, ok := x.Msg.(*OpenChannelResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *OpenChannelResponse) GetNonceShare() []byte {
	if x != nil {
		if x, ok := x.Msg.(*OpenChannelResponse_NonceShare); ok {
			return x.NonceShare
		}
	}
	return nil
}

type isOpenChannelResponse_Msg interface {
	isOpenChannelResponse_Msg()
}

type OpenChannelResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type OpenChannelResponse_NonceShare struct {
	// The NonceShare generated by the wallet.
	NonceShare []byte `protobuf:"bytes,2,opt,name=nonce_share,json=nonceShare,proto3,oneof"`
}

func (*OpenChannelResponse_Rejected) isOpenChannelResponse_Msg() {}

func (*OpenChannelResponse_NonceShare) isOpenChannelResponse_Msg() {}

type CloseChannelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The channel id of the channel to be closed.
	ChannelId []byte `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// The state with which the channel should be closed.
	State         *protobuf.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseChannelRequest) Reset() {
	*x = CloseChannelRequest{}
	mi := &file_perun_wallet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseChannelRequest) ProtoMessage() {}

func (x *CloseChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseChannelRequest.ProtoReflect.Descriptor instead.
func (*CloseChannelRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{20}
}

func (x *CloseChannelRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

func (x *CloseChannelRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

type ForceCloseChannelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The channel id of the channel to be closed.
	ChannelId []byte `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// The state with which the channel should be closed.
	State         *protobuf.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceCloseChannelRequest) Reset() {
	*x = ForceCloseChannelRequest{}
	mi := &file_perun_wallet_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceCloseChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceCloseChannelRequest) ProtoMessage() {}

func (x *ForceCloseChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceCloseChannelRequest.ProtoReflect.Descriptor instead.
func (*ForceCloseChannelRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{21}
}

func (x *ForceCloseChannelRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

func (x *ForceCloseChannelRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

type ChallengeEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The channel id of the channel which was challenged.
	ChannelId []byte `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// The state with which the channel was challenged.
	State         *protobuf.State `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeEventRequest) Reset() {
	*x = ChallengeEventRequest{}
	mi := &file_perun_wallet_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeEventRequest) ProtoMessage() {}

func (x *ChallengeEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeEventRequest.ProtoReflect.Descriptor instead.
func (*ChallengeEventRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{22}
}

func (x *ChallengeEventRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

func (x *ChallengeEventRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

type UpdateNotificationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The state with which the channel should be updated.
	State         *protobuf.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationRequest) Reset() {
	*x = UpdateNotificationRequest{}
	mi := &file_perun_wallet_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationRequest) ProtoMessage() {}

func (x *UpdateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateNotificationRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

type UpdateNotificationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether or not the channel update was accepted by the user.
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationResponse) Reset() {
	*x = UpdateNotificationResponse{}
	mi := &file_perun_wallet_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationResponse) ProtoMessage() {}

func (x *UpdateNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotificationResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateNotificationResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type SignMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public key expected to sign the given message.
	Pubkey []byte `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// The message to be signed.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignMessageRequest) Reset() {
	*x = SignMessageRequest{}
	mi := &file_perun_wallet_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessageRequest) ProtoMessage() {}

func (x *SignMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessageRequest.ProtoReflect.Descriptor instead.
func (*SignMessageRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{25}
}

func (x *SignMessageRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *SignMessageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SignMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*SignMessageResponse_Rejected
	//	*SignMessageResponse_Signature
	Msg           isSignMessageResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignMessageResponse) Reset() {
	*x = SignMessageResponse{}
	mi := &file_perun_wallet_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessageResponse) ProtoMessage() {}

func (x *SignMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessageResponse.ProtoReflect.Descriptor instead.
func (*SignMessageResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{26}
}

func (x *SignMessageResponse) GetMsg() isSignMessageResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *SignMessageResponse) GetRejected() *Rejected {
	if x != nil {
		if x, ok := x.Msg.(*SignMessageResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *SignMessageResponse) GetSignature() []byte {
	if x != nil {
		if x, ok := x.Msg.(*SignMessageResponse_Signature); ok {
			return x.Signature
		}
	}
	return nil
}

type isSignMessageResponse_Msg interface {
	isSignMessageResponse_Msg()
}

type SignMessageResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type SignMessageResponse_Signature struct {
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3,oneof"`
}

func (*SignMessageResponse_Rejected) isSignMessageResponse_Msg() {}

func (*SignMessageResponse_Signature) isSignMessageResponse_Msg() {}

type GetAssetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested assets.
	Assets        *protobuf.Balances `protobuf:"bytes,1,opt,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetsRequest) Reset() {
	*x = GetAssetsRequest{}
	mi := &file_perun_wallet_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsRequest) ProtoMessage() {}

func (x *GetAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsRequest.ProtoReflect.Descriptor instead.
func (*GetAssetsRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{27}
}

func (x *GetAssetsRequest) GetAssets() *protobuf.Balances {
	if x != nil {
		return x.Assets
	}
	return nil
}

type Asset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The asset id of the asset.
	AssetId       []byte `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_perun_wallet_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{28}
}

func (x *Asset) GetAssetId() []byte {
	if x != nil {
		return x.AssetId
	}
	return nil
}

type UnmatchableAssetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The index of the unmatchable assets from the original request.
	AssetIdx uint32 `protobuf:"varint,1,opt,name=asset_idx,json=assetIdx,proto3" json:"asset_idx,omitempty"`
	// A possible reason if more information is available.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmatchableAssetsResponse) Reset() {
	*x = UnmatchableAssetsResponse{}
	mi := &file_perun_wallet_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmatchableAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmatchableAssetsResponse) ProtoMessage() {}

func (x *UnmatchableAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmatchableAssetsResponse.ProtoReflect.Descriptor instead.
func (*UnmatchableAssetsResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{29}
}

func (x *UnmatchableAssetsResponse) GetAssetIdx() uint32 {
	if x != nil {
		return x.AssetIdx
	}
	return 0
}

func (x *UnmatchableAssetsResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetAssetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*GetAssetsResponse_Rejected
	Msg           isGetAssetsResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetsResponse) Reset() {
	*x = GetAssetsResponse{}
	mi := &file_perun_wallet_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsResponse) ProtoMessage() {}

func (x *GetAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsResponse.ProtoReflect.Descriptor instead.
func (*GetAssetsResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{30}
}

func (x *GetAssetsResponse) GetMsg() isGetAssetsResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *GetAssetsResponse) GetRejected() *UnmatchableAssetsResponse {
	if x != nil {
		if x, ok := x.Msg.(*GetAssetsResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

type isGetAssetsResponse_Msg interface {
	isGetAssetsResponse_Msg()
}

type GetAssetsResponse_Rejected struct {
	Rejected *UnmatchableAssetsResponse `protobuf:"bytes,2,opt,name=rejected,proto3,oneof"`
}

func (*GetAssetsResponse_Rejected) isGetAssetsResponse_Msg() {}

type SignTransactionRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Identifier []byte                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// The transaction to be signed.
	Transaction   []byte `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTransactionRequest) Reset() {
	*x = SignTransactionRequest{}
	mi := &file_perun_wallet_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionRequest) ProtoMessage() {}

func (x *SignTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionRequest.ProtoReflect.Descriptor instead.
func (*SignTransactionRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{31}
}

func (x *SignTransactionRequest) GetIdentifier() []byte {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *SignTransactionRequest) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SignTransactionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*SignTransactionResponse_Rejected
	//	*SignTransactionResponse_Transaction
	Msg           isSignTransactionResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTransactionResponse) Reset() {
	*x = SignTransactionResponse{}
	mi := &file_perun_wallet_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionResponse) ProtoMessage() {}

func (x *SignTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionResponse.ProtoReflect.Descriptor instead.
func (*SignTransactionResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{32}
}

func (x *SignTransactionResponse) GetMsg() isSignTransactionResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *SignTransactionResponse) GetRejected() *Rejected {
	if x != nil {
		if x, ok := x.Msg.(*SignTransactionResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *SignTransactionResponse) GetTransaction() []byte {
	if x != nil {
		if x, ok := x.Msg.(*SignTransactionResponse_Transaction); ok {
			return x.Transaction
		}
	}
	return nil
}

type isSignTransactionResponse_Msg interface {
	isSignTransactionResponse_Msg()
}

type SignTransactionResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type SignTransactionResponse_Transaction struct {
	// The signed transaction.
	Transaction []byte `protobuf:"bytes,2,opt,name=transaction,proto3,oneof"`
}

func (*SignTransactionResponse_Rejected) isSignTransactionResponse_Msg() {}

func (*SignTransactionResponse_Transaction) isSignTransactionResponse_Msg() {}

var File_perun_wallet_proto protoreflect.FileDescriptor

const file_perun_wallet_proto_rawDesc = "" +
	"\n" +
	"\x12perun-wallet.proto\x12\fperunservice\x1a\n" +
	"wire.proto\",\n" +
	"\x16RestoreChannelsRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"I\n" +
	"\x17RestoreChannelsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"-\n" +
	"\x17ClosePerunClientRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"J\n" +
	"\x18ClosePerunClientResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"+\n" +
	"\x15NewPerunClientRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"H\n" +
	"\x16NewPerunClientResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\"\n" +
	"\bRejected\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"2\n" +
	"\x12GetChannelsRequest\x12\x1c\n" +
	"\trequester\x18\x01 \x01(\fR\trequester\"\x98\x01\n" +
	"\x13GetChannelsResponse\x124\n" +
	"\brejected\x18\x01 \x01(\v2\x16.perunservice.RejectedH\x00R\brejected\x12D\n" +
	"\x0echannel_states\x18\x02 \x01(\v2\x1b.perunservice.ChannelStatesH\x00R\rchannelStatesB\x05\n" +
	"\x03msg\"X\n" +
	"\rChannelStates\x12(\n" +
	"\x06states\x18\x01 \x03(\v2\x10.perunwire.StateR\x06states\x12\x1d\n" +
	"\n" +
	"actor_idxs\x18\x02 \x03(\rR\tactorIdxs\"\xac\x01\n" +
	"\x12ChannelOpenRequest\x12\x1c\n" +
	"\trequester\x18\x01 \x01(\fR\trequester\x12\x12\n" +
	"\x04peer\x18\x02 \x01(\fR\x04peer\x125\n" +
	"\n" +
	"allocation\x18\x03 \x01(\v2\x15.perunwire.AllocationR\n" +
	"allocation\x12-\n" +
	"\x12challenge_duration\x18\x04 \x01(\x04R\x11challengeDuration\"s\n" +
	"\x13ChannelOpenResponse\x124\n" +
	"\brejected\x18\x01 \x01(\v2\x16.perunservice.RejectedH\x00R\brejected\x12\x1f\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\fH\x00R\tchannelIdB\x05\n" +
	"\x03msg\">\n" +
	"\x14ChannelUpdateRequest\x12&\n" +
	"\x05state\x18\x01 \x01(\v2\x10.perunwire.StateR\x05state\"Y\n" +
	"\x10SuccessfulUpdate\x12&\n" +
	"\x05state\x18\x01 \x01(\v2\x10.perunwire.StateR\x05state\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\fR\tchannelId\"\x8e\x01\n" +
	"\x15ChannelUpdateResponse\x124\n" +
	"\brejected\x18\x01 \x01(\v2\x16.perunservice.RejectedH\x00R\brejected\x128\n" +
	"\x06update\x18\x02 \x01(\v2\x1e.perunservice.SuccessfulUpdateH\x00R\x06updateB\x05\n" +
	"\x03msg\"4\n" +
	"\x13ChannelCloseRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\fR\tchannelId\"0\n" +
	"\x0fSuccessfulClose\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\fR\tchannelId\"\x8a\x01\n" +
	"\x14ChannelCloseResponse\x124\n" +
	"\brejected\x18\x01 \x01(\v2\x16.perunservice.RejectedH\x00R\brejected\x125\n" +
	"\x05close\x18\x02 \x01(\v2\x1d.perunservice.SuccessfulCloseH\x00R\x05closeB\x05\n" +
	"\x03msg\"U\n" +
	"\x12OpenChannelRequest\x12?\n" +
	"\bproposal\x18\x01 \x01(\v2#.perunwire.LedgerChannelProposalMsgR\bproposal\"u\n" +
	"\x13OpenChannelResponse\x124\n" +
	"\brejected\x18\x01 \x01(\v2\x16.perunservice.RejectedH\x00R\brejected\x12!\n" +
	"\vnonce_share\x18\x02 \x01(\fH\x00R\n" +
	"nonceShareB\x05\n" +
	"\x03msg\"\\\n" +
	"\x13CloseChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\fR\tchannelId\x12&\n" +
	"\x05state\x18\x01 \x01(\v2\x10.perunwire.StateR\x05state\"a\n" +
	"\x18ForceCloseChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\fR\tchannelId\x12&\n" +
	"\x05state\x18\x01 \x01(\v2\x10.perunwire.StateR\x05state\"^\n" +
	"\x15ChallengeEventRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\fR\tchannelId\x12&\n" +
	"\x05state\x18\x02 \x01(\v2\x10.perunwire.StateR\x05state\"C\n" +
	"\x19UpdateNotificationRequest\x12&\n" +
	"\x05state\x18\x01 \x01(\v2\x10.perunwire.StateR\x05state\"8\n" +
	"\x1aUpdateNotificationResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"@\n" +
	"\x12SignMessageRequest\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"r\n" +
	"\x13SignMessageResponse\x124\n" +
	"\brejected\x18\x01 \x01(\v2\x16.perunservice.RejectedH\x00R\brejected\x12\x1e\n" +
	"\tsignature\x18\x02 \x01(\fH\x00R\tsignatureB\x05\n" +
	"\x03msg\"?\n" +
	"\x10GetAssetsRequest\x12+\n" +
	"\x06assets\x18\x01 \x01(\v2\x13.perunwire.BalancesR\x06assets\"\"\n" +
	"\x05Asset\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\fR\aassetId\"P\n" +
	"\x19UnmatchableAssetsResponse\x12\x1b\n" +
	"\tasset_idx\x18\x01 \x01(\rR\bassetIdx\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"a\n" +
	"\x11GetAssetsResponse\x12E\n" +
	"\brejected\x18\x02 \x01(\v2'.perunservice.UnmatchableAssetsResponseH\x00R\brejectedB\x05\n" +
	"\x03msg\"Z\n" +
	"\x16SignTransactionRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\fR\n" +
	"identifier\x12 \n" +
	"\vtransaction\x18\x02 \x01(\fR\vtransaction\"z\n" +
	"\x17SignTransactionResponse\x124\n" +
	"\brejected\x18\x01 \x01(\v2\x16.perunservice.RejectedH\x00R\brejected\x12\"\n" +
	"\vtransaction\x18\x02 \x01(\fH\x00R\vtransactionB\x05\n" +
	"\x03msg2\x89\x05\n" +
	"\x0eChannelService\x12R\n" +
	"\vOpenChannel\x12 .perunservice.ChannelOpenRequest\x1a!.perunservice.ChannelOpenResponse\x12X\n" +
	"\rUpdateChannel\x12\".perunservice.ChannelUpdateRequest\x1a#.perunservice.ChannelUpdateResponse\x12U\n" +
	"\fCloseChannel\x12!.perunservice.ChannelCloseRequest\x1a\".perunservice.ChannelCloseResponse\x12R\n" +
	"\vGetChannels\x12 .perunservice.GetChannelsRequest\x1a!.perunservice.GetChannelsResponse\x12^\n" +
	"\x0fRestoreChannels\x12$.perunservice.RestoreChannelsRequest\x1a%.perunservice.RestoreChannelsResponse\x12a\n" +
	"\x10ClosePerunClient\x12%.perunservice.ClosePerunClientRequest\x1a&.perunservice.ClosePerunClientResponse\x12[\n" +
	"\x0eNewPerunClient\x12#.perunservice.NewPerunClientRequest\x1a$.perunservice.NewPerunClientResponse2\xce\x03\n" +
	"\rWalletService\x12R\n" +
	"\vOpenChannel\x12 .perunservice.OpenChannelRequest\x1a!.perunservice.OpenChannelResponse\x12g\n" +
	"\x12UpdateNotification\x12'.perunservice.UpdateNotificationRequest\x1a(.perunservice.UpdateNotificationResponse\x12R\n" +
	"\vSignMessage\x12 .perunservice.SignMessageRequest\x1a!.perunservice.SignMessageResponse\x12^\n" +
	"\x0fSignTransaction\x12$.perunservice.SignTransactionRequest\x1a%.perunservice.SignTransactionResponse\x12L\n" +
	"\tGetAssets\x12\x1e.perunservice.GetAssetsRequest\x1a\x1f.perunservice.GetAssetsResponseB\tZ\a./protob\x06proto3"

var (
	file_perun_wallet_proto_rawDescOnce sync.Once
	file_perun_wallet_proto_rawDescData []byte
)

func file_perun_wallet_proto_rawDescGZIP() []byte {
	file_perun_wallet_proto_rawDescOnce.Do(func() {
		file_perun_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_perun_wallet_proto_rawDesc), len(file_perun_wallet_proto_rawDesc)))
	})
	return file_perun_wallet_proto_rawDescData
}

var file_perun_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_perun_wallet_proto_goTypes = []any{
	(*RestoreChannelsRequest)(nil),            // 0: perunservice.RestoreChannelsRequest
	(*RestoreChannelsResponse)(nil),           // 1: perunservice.RestoreChannelsResponse
	(*ClosePerunClientRequest)(nil),           // 2: perunservice.ClosePerunClientRequest
	(*ClosePerunClientResponse)(nil),          // 3: perunservice.ClosePerunClientResponse
	(*NewPerunClientRequest)(nil),             // 4: perunservice.NewPerunClientRequest
	(*NewPerunClientResponse)(nil),            // 5: perunservice.NewPerunClientResponse
	(*Rejected)(nil),                          // 6: perunservice.Rejected
	(*GetChannelsRequest)(nil),                // 7: perunservice.GetChannelsRequest
	(*GetChannelsResponse)(nil),               // 8: perunservice.GetChannelsResponse
	(*ChannelStates)(nil),                     // 9: perunservice.ChannelStates
	(*ChannelOpenRequest)(nil),                // 10: perunservice.ChannelOpenRequest
	(*ChannelOpenResponse)(nil),               // 11: perunservice.ChannelOpenResponse
	(*ChannelUpdateRequest)(nil),              // 12: perunservice.ChannelUpdateRequest
	(*SuccessfulUpdate)(nil),                  // 13: perunservice.SuccessfulUpdate
	(*ChannelUpdateResponse)(nil),             // 14: perunservice.ChannelUpdateResponse
	(*ChannelCloseRequest)(nil),               // 15: perunservice.ChannelCloseRequest
	(*SuccessfulClose)(nil),                   // 16: perunservice.SuccessfulClose
	(*ChannelCloseResponse)(nil),              // 17: perunservice.ChannelCloseResponse
	(*OpenChannelRequest)(nil),                // 18: perunservice.OpenChannelRequest
	(*OpenChannelResponse)(nil),               // 19: perunservice.OpenChannelResponse
	(*CloseChannelRequest)(nil),               // 20: perunservice.CloseChannelRequest
	(*ForceCloseChannelRequest)(nil),          // 21: perunservice.ForceCloseChannelRequest
	(*ChallengeEventRequest)(nil),             // 22: perunservice.ChallengeEventRequest
	(*UpdateNotificationRequest)(nil),         // 23: perunservice.UpdateNotificationRequest
	(*UpdateNotificationResponse)(nil),        // 24: perunservice.UpdateNotificationResponse
	(*SignMessageRequest)(nil),                // 25: perunservice.SignMessageRequest
	(*SignMessageResponse)(nil),               // 26: perunservice.SignMessageResponse
	(*GetAssetsRequest)(nil),                  // 27: perunservice.GetAssetsRequest
	(*Asset)(nil),                             // 28: perunservice.Asset
	(*UnmatchableAssetsResponse)(nil),         // 29: perunservice.UnmatchableAssetsResponse
	(*GetAssetsResponse)(nil),                 // 30: perunservice.GetAssetsResponse
	(*SignTransactionRequest)(nil),            // 31: perunservice.SignTransactionRequest
	(*SignTransactionResponse)(nil),           // 32: perunservice.SignTransactionResponse
	(*protobuf.State)(nil),                    // 33: perunwire.State
	(*protobuf.Allocation)(nil),               // 34: perunwire.Allocation
	(*protobuf.LedgerChannelProposalMsg)(nil), // 35: perunwire.LedgerChannelProposalMsg
	(*protobuf.Balances)(nil),                 // 36: perunwire.Balances
}
var file_perun_wallet_proto_depIdxs = []int32{
	6,  // 0: perunservice.GetChannelsResponse.rejected:type_name -> perunservice.Rejected
	9,  // 1: perunservice.GetChannelsResponse.channel_states:type_name -> perunservice.ChannelStates
	33, // 2: perunservice.ChannelStates.states:type_name -> perunwire.State
	34, // 3: perunservice.ChannelOpenRequest.allocation:type_name -> perunwire.Allocation
	6,  // 4: perunservice.ChannelOpenResponse.rejected:type_name -> perunservice.Rejected
	33, // 5: perunservice.ChannelUpdateRequest.state:type_name -> perunwire.State
	33, // 6: perunservice.SuccessfulUpdate.state:type_name -> perunwire.State
	6,  // 7: perunservice.ChannelUpdateResponse.rejected:type_name -> perunservice.Rejected
	13, // 8: perunservice.ChannelUpdateResponse.update:type_name -> perunservice.SuccessfulUpdate
	6,  // 9: perunservice.ChannelCloseResponse.rejected:type_name -> perunservice.Rejected
	16, // 10: perunservice.ChannelCloseResponse.close:type_name -> perunservice.SuccessfulClose
	35, // 11: perunservice.OpenChannelRequest.proposal:type_name -> perunwire.LedgerChannelProposalMsg
	6,  // 12: perunservice.OpenChannelResponse.rejected:type_name -> perunservice.Rejected
	33, // 13: perunservice.CloseChannelRequest.state:type_name -> perunwire.State
	33, // 14: perunservice.ForceCloseChannelRequest.state:type_name -> perunwire.State
	33, // 15: perunservice.ChallengeEventRequest.state:type_name -> perunwire.State
	33, // 16: perunservice.UpdateNotificationRequest.state:type_name -> perunwire.State
	6,  // 17: perunservice.SignMessageResponse.rejected:type_name -> perunservice.Rejected
	36, // 18: perunservice.GetAssetsRequest.assets:type_name -> perunwire.Balances
	29, // 19: perunservice.GetAssetsResponse.rejected:type_name -> perunservice.UnmatchableAssetsResponse
	6,  // 20: perunservice.SignTransactionResponse.rejected:type_name -> perunservice.Rejected
	10, // 21: perunservice.ChannelService.OpenChannel:input_type -> perunservice.ChannelOpenRequest
	12, // 22: perunservice.ChannelService.UpdateChannel:input_type -> perunservice.ChannelUpdateRequest
	15, // 23: perunservice.ChannelService.CloseChannel:input_type -> perunservice.ChannelCloseRequest
	7,  // 24: perunservice.ChannelService.GetChannels:input_type -> perunservice.GetChannelsRequest
	0,  // 25: perunservice.ChannelService.RestoreChannels:input_type -> perunservice.RestoreChannelsRequest
	2,  // 26: perunservice.ChannelService.ClosePerunClient:input_type -> perunservice.ClosePerunClientRequest
	4,  // 27: perunservice.ChannelService.NewPerunClient:input_type -> perunservice.NewPerunClientRequest
	18, // 28: perunservice.WalletService.OpenChannel:input_type -> perunservice.OpenChannelRequest
	23, // 29: perunservice.WalletService.UpdateNotification:input_type -> perunservice.UpdateNotificationRequest
	25, // 30: perunservice.WalletService.SignMessage:input_type -> perunservice.SignMessageRequest
	31, // 31: perunservice.WalletService.SignTransaction:input_type -> perunservice.SignTransactionRequest
	27, // 32: perunservice.WalletService.GetAssets:input_type -> perunservice.GetAssetsRequest
	11, // 33: perunservice.ChannelService.OpenChannel:output_type -> perunservice.ChannelOpenResponse
	14, // 34: perunservice.ChannelService.UpdateChannel:output_type -> perunservice.ChannelUpdateResponse
	17, // 35: perunservice.ChannelService.CloseChannel:output_type -> perunservice.ChannelCloseResponse
	8,  // 36: perunservice.ChannelService.GetChannels:output_type -> perunservice.GetChannelsResponse
	1,  // 37: perunservice.ChannelService.RestoreChannels:output_type -> perunservice.RestoreChannelsResponse
	3,  // 38: perunservice.ChannelService.ClosePerunClient:output_type -> perunservice.ClosePerunClientResponse
	5,  // 39: perunservice.ChannelService.NewPerunClient:output_type -> perunservice.NewPerunClientResponse
	19, // 40: perunservice.WalletService.OpenChannel:output_type -> perunservice.OpenChannelResponse
	24, // 41: perunservice.WalletService.UpdateNotification:output_type -> perunservice.UpdateNotificationResponse
	26, // 42: perunservice.WalletService.SignMessage:output_type -> perunservice.SignMessageResponse
	32, // 43: perunservice.WalletService.SignTransaction:output_type -> perunservice.SignTransactionResponse
	30, // 44: perunservice.WalletService.GetAssets:output_type -> perunservice.GetAssetsResponse
	33, // [33:45] is the sub-list for method output_type
	21, // [21:33] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_perun_wallet_proto_init() }
func file_perun_wallet_proto_init() {
	if File_perun_wallet_proto != nil {
		return
	}
	file_perun_wallet_proto_msgTypes[8].OneofWrappers = []any{
		(*GetChannelsResponse_Rejected)(nil),
		(*GetChannelsResponse_ChannelStates)(nil),
	}
	file_perun_wallet_proto_msgTypes[11].OneofWrappers = []any{
		(*ChannelOpenResponse_Rejected)(nil),
		(*ChannelOpenResponse_ChannelId)(nil),
	}
	file_perun_wallet_proto_msgTypes[14].OneofWrappers = []any{
		(*ChannelUpdateResponse_Rejected)(nil),
		(*ChannelUpdateResponse_Update)(nil),
	}
	file_perun_wallet_proto_msgTypes[17].OneofWrappers = []any{
		(*ChannelCloseResponse_Rejected)(nil),
		(*ChannelCloseResponse_Close)(nil),
	}
	file_perun_wallet_proto_msgTypes[19].OneofWrappers = []any{
		(*OpenChannelResponse_Rejected)(nil),
		(*OpenChannelResponse_NonceShare)(nil),
	}
	file_perun_wallet_proto_msgTypes[26].OneofWrappers = []any{
		(*SignMessageResponse_Rejected)(nil),
		(*SignMessageResponse_Signature)(nil),
	}
	file_perun_wallet_proto_msgTypes[30].OneofWrappers = []any{
		(*GetAssetsResponse_Rejected)(nil),
	}
	file_perun_wallet_proto_msgTypes[32].OneofWrappers = []any{
		(*SignTransactionResponse_Rejected)(nil),
		(*SignTransactionResponse_Transaction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_perun_wallet_proto_rawDesc), len(file_perun_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_perun_wallet_proto_goTypes,
		DependencyIndexes: file_perun_wallet_proto_depIdxs,
		MessageInfos:      file_perun_wallet_proto_msgTypes,
	}.Build()
	File_perun_wallet_proto = out.File
	file_perun_wallet_proto_goTypes = nil
	file_perun_wallet_proto_depIdxs = nil
}
