// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.2
// source: perun-wallet.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	protobuf "perun.network/go-perun/wire/protobuf"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generic rejected message. Returned by any endpoint on failure.
type Rejected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Rejected) Reset() {
	*x = Rejected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rejected) ProtoMessage() {}

func (x *Rejected) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rejected.ProtoReflect.Descriptor instead.
func (*Rejected) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *Rejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ChannelOpenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peer   []byte  `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Assets *Assets `protobuf:"bytes,2,opt,name=assets,proto3" json:"assets,omitempty"`
}

func (x *ChannelOpenRequest) Reset() {
	*x = ChannelOpenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelOpenRequest) ProtoMessage() {}

func (x *ChannelOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelOpenRequest.ProtoReflect.Descriptor instead.
func (*ChannelOpenRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelOpenRequest) GetPeer() []byte {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *ChannelOpenRequest) GetAssets() *Assets {
	if x != nil {
		return x.Assets
	}
	return nil
}

type ChannelOpenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*ChannelOpenResponse_Rejected
	//	*ChannelOpenResponse_ChannelId
	Msg isChannelOpenResponse_Msg `protobuf_oneof:"msg"`
}

func (x *ChannelOpenResponse) Reset() {
	*x = ChannelOpenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelOpenResponse) ProtoMessage() {}

func (x *ChannelOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelOpenResponse.ProtoReflect.Descriptor instead.
func (*ChannelOpenResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{2}
}

func (m *ChannelOpenResponse) GetMsg() isChannelOpenResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ChannelOpenResponse) GetRejected() *Rejected {
	if x, ok := x.GetMsg().(*ChannelOpenResponse_Rejected); ok {
		return x.Rejected
	}
	return nil
}

func (x *ChannelOpenResponse) GetChannelId() []byte {
	if x, ok := x.GetMsg().(*ChannelOpenResponse_ChannelId); ok {
		return x.ChannelId
	}
	return nil
}

type isChannelOpenResponse_Msg interface {
	isChannelOpenResponse_Msg()
}

type ChannelOpenResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type ChannelOpenResponse_ChannelId struct {
	ChannelId []byte `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3,oneof"`
}

func (*ChannelOpenResponse_Rejected) isChannelOpenResponse_Msg() {}

func (*ChannelOpenResponse_ChannelId) isChannelOpenResponse_Msg() {}

type ChannelUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The state with which the channel should be updated.
	State *protobuf.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// The channel id of the channel to be updated.
	ChannelId []byte `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (x *ChannelUpdateRequest) Reset() {
	*x = ChannelUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelUpdateRequest) ProtoMessage() {}

func (x *ChannelUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelUpdateRequest.ProtoReflect.Descriptor instead.
func (*ChannelUpdateRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelUpdateRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ChannelUpdateRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type SuccessfulUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The state with which the channel was updated.
	State *protobuf.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// The channel id of the channel which was updated.
	ChannelId []byte `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (x *SuccessfulUpdate) Reset() {
	*x = SuccessfulUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessfulUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessfulUpdate) ProtoMessage() {}

func (x *SuccessfulUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessfulUpdate.ProtoReflect.Descriptor instead.
func (*SuccessfulUpdate) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *SuccessfulUpdate) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *SuccessfulUpdate) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type ChannelUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*ChannelUpdateResponse_Rejected
	//	*ChannelUpdateResponse_Update
	Msg isChannelUpdateResponse_Msg `protobuf_oneof:"msg"`
}

func (x *ChannelUpdateResponse) Reset() {
	*x = ChannelUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelUpdateResponse) ProtoMessage() {}

func (x *ChannelUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelUpdateResponse.ProtoReflect.Descriptor instead.
func (*ChannelUpdateResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{5}
}

func (m *ChannelUpdateResponse) GetMsg() isChannelUpdateResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ChannelUpdateResponse) GetRejected() *Rejected {
	if x, ok := x.GetMsg().(*ChannelUpdateResponse_Rejected); ok {
		return x.Rejected
	}
	return nil
}

func (x *ChannelUpdateResponse) GetUpdate() *SuccessfulUpdate {
	if x, ok := x.GetMsg().(*ChannelUpdateResponse_Update); ok {
		return x.Update
	}
	return nil
}

type isChannelUpdateResponse_Msg interface {
	isChannelUpdateResponse_Msg()
}

type ChannelUpdateResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type ChannelUpdateResponse_Update struct {
	Update *SuccessfulUpdate `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

func (*ChannelUpdateResponse_Rejected) isChannelUpdateResponse_Msg() {}

func (*ChannelUpdateResponse_Update) isChannelUpdateResponse_Msg() {}

type ChannelCloseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The channel id of the channel to be closed.
	ChannelId []byte `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (x *ChannelCloseRequest) Reset() {
	*x = ChannelCloseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCloseRequest) ProtoMessage() {}

func (x *ChannelCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCloseRequest.ProtoReflect.Descriptor instead.
func (*ChannelCloseRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *ChannelCloseRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type SuccessfulClose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The channel id of the channel which was closed.
	ChannelId []byte `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (x *SuccessfulClose) Reset() {
	*x = SuccessfulClose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessfulClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessfulClose) ProtoMessage() {}

func (x *SuccessfulClose) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessfulClose.ProtoReflect.Descriptor instead.
func (*SuccessfulClose) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *SuccessfulClose) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type ChannelCloseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*ChannelCloseResponse_Rejected
	//	*ChannelCloseResponse_Close
	Msg isChannelCloseResponse_Msg `protobuf_oneof:"msg"`
}

func (x *ChannelCloseResponse) Reset() {
	*x = ChannelCloseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCloseResponse) ProtoMessage() {}

func (x *ChannelCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCloseResponse.ProtoReflect.Descriptor instead.
func (*ChannelCloseResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{8}
}

func (m *ChannelCloseResponse) GetMsg() isChannelCloseResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ChannelCloseResponse) GetRejected() *Rejected {
	if x, ok := x.GetMsg().(*ChannelCloseResponse_Rejected); ok {
		return x.Rejected
	}
	return nil
}

func (x *ChannelCloseResponse) GetClose() *SuccessfulClose {
	if x, ok := x.GetMsg().(*ChannelCloseResponse_Close); ok {
		return x.Close
	}
	return nil
}

type isChannelCloseResponse_Msg interface {
	isChannelCloseResponse_Msg()
}

type ChannelCloseResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type ChannelCloseResponse_Close struct {
	Close *SuccessfulClose `protobuf:"bytes,2,opt,name=close,proto3,oneof"`
}

func (*ChannelCloseResponse_Rejected) isChannelCloseResponse_Msg() {}

func (*ChannelCloseResponse_Close) isChannelCloseResponse_Msg() {}

type ChannelForceCloseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The channel id of the channel to be force closed.
	ChannelId []byte `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (x *ChannelForceCloseRequest) Reset() {
	*x = ChannelForceCloseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelForceCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelForceCloseRequest) ProtoMessage() {}

func (x *ChannelForceCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelForceCloseRequest.ProtoReflect.Descriptor instead.
func (*ChannelForceCloseRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *ChannelForceCloseRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type SuccessfulForceClose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The channel id of the channel which was force closed.
	ChannelId []byte `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (x *SuccessfulForceClose) Reset() {
	*x = SuccessfulForceClose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessfulForceClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessfulForceClose) ProtoMessage() {}

func (x *SuccessfulForceClose) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessfulForceClose.ProtoReflect.Descriptor instead.
func (*SuccessfulForceClose) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *SuccessfulForceClose) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type ChannelForceCloseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*ChannelForceCloseResponse_Rejected
	//	*ChannelForceCloseResponse_Close
	Msg isChannelForceCloseResponse_Msg `protobuf_oneof:"msg"`
}

func (x *ChannelForceCloseResponse) Reset() {
	*x = ChannelForceCloseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelForceCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelForceCloseResponse) ProtoMessage() {}

func (x *ChannelForceCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelForceCloseResponse.ProtoReflect.Descriptor instead.
func (*ChannelForceCloseResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{11}
}

func (m *ChannelForceCloseResponse) GetMsg() isChannelForceCloseResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ChannelForceCloseResponse) GetRejected() *Rejected {
	if x, ok := x.GetMsg().(*ChannelForceCloseResponse_Rejected); ok {
		return x.Rejected
	}
	return nil
}

func (x *ChannelForceCloseResponse) GetClose() *SuccessfulClose {
	if x, ok := x.GetMsg().(*ChannelForceCloseResponse_Close); ok {
		return x.Close
	}
	return nil
}

type isChannelForceCloseResponse_Msg interface {
	isChannelForceCloseResponse_Msg()
}

type ChannelForceCloseResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type ChannelForceCloseResponse_Close struct {
	Close *SuccessfulClose `protobuf:"bytes,2,opt,name=close,proto3,oneof"`
}

func (*ChannelForceCloseResponse_Rejected) isChannelForceCloseResponse_Msg() {}

func (*ChannelForceCloseResponse_Close) isChannelForceCloseResponse_Msg() {}

type ChallengeChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The channel id of the channel to be challenged.
	ChannelId []byte `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// The state with which the channel should be challenged.
	State *protobuf.State `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ChallengeChannelRequest) Reset() {
	*x = ChallengeChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChallengeChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeChannelRequest) ProtoMessage() {}

func (x *ChallengeChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeChannelRequest.ProtoReflect.Descriptor instead.
func (*ChallengeChannelRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *ChallengeChannelRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

func (x *ChallengeChannelRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

type ChallengeChannelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*ChallengeChannelResponse_Rejected
	//	*ChallengeChannelResponse_Update
	Msg isChallengeChannelResponse_Msg `protobuf_oneof:"msg"`
}

func (x *ChallengeChannelResponse) Reset() {
	*x = ChallengeChannelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChallengeChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeChannelResponse) ProtoMessage() {}

func (x *ChallengeChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeChannelResponse.ProtoReflect.Descriptor instead.
func (*ChallengeChannelResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{13}
}

func (m *ChallengeChannelResponse) GetMsg() isChallengeChannelResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ChallengeChannelResponse) GetRejected() *Rejected {
	if x, ok := x.GetMsg().(*ChallengeChannelResponse_Rejected); ok {
		return x.Rejected
	}
	return nil
}

func (x *ChallengeChannelResponse) GetUpdate() *SuccessfulUpdate {
	if x, ok := x.GetMsg().(*ChallengeChannelResponse_Update); ok {
		return x.Update
	}
	return nil
}

type isChallengeChannelResponse_Msg interface {
	isChallengeChannelResponse_Msg()
}

type ChallengeChannelResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type ChallengeChannelResponse_Update struct {
	// In case the challenge was successful return the updated channel state.
	// Can be used for confirmation in the frontend.
	Update *SuccessfulUpdate `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

func (*ChallengeChannelResponse_Rejected) isChallengeChannelResponse_Msg() {}

func (*ChallengeChannelResponse_Update) isChallengeChannelResponse_Msg() {}

// Called by the Perun channel service if it received a channel opening request
// from another peer. The proposed channel state is passed to the wallet which
// might use it to show it in to the user.
type OpenChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The state with which the channel should be opened.
	State *protobuf.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// The channel id of the channel to be opened.
	ChannelId []byte `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (x *OpenChannelRequest) Reset() {
	*x = OpenChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenChannelRequest) ProtoMessage() {}

func (x *OpenChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenChannelRequest.ProtoReflect.Descriptor instead.
func (*OpenChannelRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{14}
}

func (x *OpenChannelRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *OpenChannelRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type CloseChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The channel id of the channel to be closed.
	ChannelId []byte `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// The state with which the channel should be closed.
	State *protobuf.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *CloseChannelRequest) Reset() {
	*x = CloseChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseChannelRequest) ProtoMessage() {}

func (x *CloseChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseChannelRequest.ProtoReflect.Descriptor instead.
func (*CloseChannelRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{15}
}

func (x *CloseChannelRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

func (x *CloseChannelRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

type ForceCloseChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The channel id of the channel to be closed.
	ChannelId []byte `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// The state with which the channel should be closed.
	State *protobuf.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ForceCloseChannelRequest) Reset() {
	*x = ForceCloseChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForceCloseChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceCloseChannelRequest) ProtoMessage() {}

func (x *ForceCloseChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceCloseChannelRequest.ProtoReflect.Descriptor instead.
func (*ForceCloseChannelRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{16}
}

func (x *ForceCloseChannelRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

func (x *ForceCloseChannelRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

type ChallengeEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The channel id of the channel which was challenged.
	ChannelId []byte `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// The state with which the channel was challenged.
	State *protobuf.State `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ChallengeEventRequest) Reset() {
	*x = ChallengeEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChallengeEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeEventRequest) ProtoMessage() {}

func (x *ChallengeEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeEventRequest.ProtoReflect.Descriptor instead.
func (*ChallengeEventRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{17}
}

func (x *ChallengeEventRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

func (x *ChallengeEventRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

type UpdateNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The state with which the channel should be updated.
	State *protobuf.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// The channel id of the channel to be updated.
	ChannelId []byte `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (x *UpdateNotificationRequest) Reset() {
	*x = UpdateNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationRequest) ProtoMessage() {}

func (x *UpdateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateNotificationRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *UpdateNotificationRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type UpdateNotificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Whether or not the channel update was accepted by the user.
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *UpdateNotificationResponse) Reset() {
	*x = UpdateNotificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationResponse) ProtoMessage() {}

func (x *UpdateNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotificationResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateNotificationResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type SignMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The message to be signed.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SignMessageRequest) Reset() {
	*x = SignMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessageRequest) ProtoMessage() {}

func (x *SignMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessageRequest.ProtoReflect.Descriptor instead.
func (*SignMessageRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{20}
}

func (x *SignMessageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SignMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*SignMessageResponse_Rejected
	//	*SignMessageResponse_Signature
	Msg isSignMessageResponse_Msg `protobuf_oneof:"msg"`
}

func (x *SignMessageResponse) Reset() {
	*x = SignMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessageResponse) ProtoMessage() {}

func (x *SignMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessageResponse.ProtoReflect.Descriptor instead.
func (*SignMessageResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{21}
}

func (m *SignMessageResponse) GetMsg() isSignMessageResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *SignMessageResponse) GetRejected() *Rejected {
	if x, ok := x.GetMsg().(*SignMessageResponse_Rejected); ok {
		return x.Rejected
	}
	return nil
}

func (x *SignMessageResponse) GetSignature() []byte {
	if x, ok := x.GetMsg().(*SignMessageResponse_Signature); ok {
		return x.Signature
	}
	return nil
}

type isSignMessageResponse_Msg interface {
	isSignMessageResponse_Msg()
}

type SignMessageResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type SignMessageResponse_Signature struct {
	// The signature of the message.
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3,oneof"`
}

func (*SignMessageResponse_Rejected) isSignMessageResponse_Msg() {}

func (*SignMessageResponse_Signature) isSignMessageResponse_Msg() {}

type GetAssetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The requested assets.
	Assets *protobuf.Balances `protobuf:"bytes,1,opt,name=assets,proto3" json:"assets,omitempty"`
}

func (x *GetAssetsRequest) Reset() {
	*x = GetAssetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsRequest) ProtoMessage() {}

func (x *GetAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsRequest.ProtoReflect.Descriptor instead.
func (*GetAssetsRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{22}
}

func (x *GetAssetsRequest) GetAssets() *protobuf.Balances {
	if x != nil {
		return x.Assets
	}
	return nil
}

type Asset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The asset id of the asset.
	AssetId []byte `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// A list of outpoints of the given asset_id.
	Outpoints [][]byte `protobuf:"bytes,2,rep,name=outpoints,proto3" json:"outpoints,omitempty"`
}

func (x *Asset) Reset() {
	*x = Asset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{23}
}

func (x *Asset) GetAssetId() []byte {
	if x != nil {
		return x.AssetId
	}
	return nil
}

func (x *Asset) GetOutpoints() [][]byte {
	if x != nil {
		return x.Outpoints
	}
	return nil
}

type Assets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Assets []*Asset `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
}

func (x *Assets) Reset() {
	*x = Assets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Assets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assets) ProtoMessage() {}

func (x *Assets) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assets.ProtoReflect.Descriptor instead.
func (*Assets) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{24}
}

func (x *Assets) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type UnmatchableAssetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The index of the unmatchable assets from the original request.
	AssetIdx uint32 `protobuf:"varint,1,opt,name=asset_idx,json=assetIdx,proto3" json:"asset_idx,omitempty"`
	// A possible reason if more information is available.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *UnmatchableAssetsResponse) Reset() {
	*x = UnmatchableAssetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnmatchableAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmatchableAssetsResponse) ProtoMessage() {}

func (x *UnmatchableAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmatchableAssetsResponse.ProtoReflect.Descriptor instead.
func (*UnmatchableAssetsResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{25}
}

func (x *UnmatchableAssetsResponse) GetAssetIdx() uint32 {
	if x != nil {
		return x.AssetIdx
	}
	return 0
}

func (x *UnmatchableAssetsResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetAssetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*GetAssetsResponse_Rejected
	//	*GetAssetsResponse_Assets
	Msg isGetAssetsResponse_Msg `protobuf_oneof:"msg"`
}

func (x *GetAssetsResponse) Reset() {
	*x = GetAssetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsResponse) ProtoMessage() {}

func (x *GetAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsResponse.ProtoReflect.Descriptor instead.
func (*GetAssetsResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{26}
}

func (m *GetAssetsResponse) GetMsg() isGetAssetsResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *GetAssetsResponse) GetRejected() *UnmatchableAssetsResponse {
	if x, ok := x.GetMsg().(*GetAssetsResponse_Rejected); ok {
		return x.Rejected
	}
	return nil
}

func (x *GetAssetsResponse) GetAssets() *Assets {
	if x, ok := x.GetMsg().(*GetAssetsResponse_Assets); ok {
		return x.Assets
	}
	return nil
}

type isGetAssetsResponse_Msg interface {
	isGetAssetsResponse_Msg()
}

type GetAssetsResponse_Rejected struct {
	Rejected *UnmatchableAssetsResponse `protobuf:"bytes,2,opt,name=rejected,proto3,oneof"`
}

type GetAssetsResponse_Assets struct {
	Assets *Assets `protobuf:"bytes,1,opt,name=assets,proto3,oneof"`
}

func (*GetAssetsResponse_Rejected) isGetAssetsResponse_Msg() {}

func (*GetAssetsResponse_Assets) isGetAssetsResponse_Msg() {}

type SignTransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The transaction to be signed.
	Transaction []byte `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
}

func (x *SignTransactionRequest) Reset() {
	*x = SignTransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionRequest) ProtoMessage() {}

func (x *SignTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionRequest.ProtoReflect.Descriptor instead.
func (*SignTransactionRequest) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{27}
}

func (x *SignTransactionRequest) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SignTransactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*SignTransactionResponse_Rejected
	//	*SignTransactionResponse_Signature
	Msg isSignTransactionResponse_Msg `protobuf_oneof:"msg"`
}

func (x *SignTransactionResponse) Reset() {
	*x = SignTransactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perun_wallet_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionResponse) ProtoMessage() {}

func (x *SignTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_perun_wallet_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionResponse.ProtoReflect.Descriptor instead.
func (*SignTransactionResponse) Descriptor() ([]byte, []int) {
	return file_perun_wallet_proto_rawDescGZIP(), []int{28}
}

func (m *SignTransactionResponse) GetMsg() isSignTransactionResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *SignTransactionResponse) GetRejected() *Rejected {
	if x, ok := x.GetMsg().(*SignTransactionResponse_Rejected); ok {
		return x.Rejected
	}
	return nil
}

func (x *SignTransactionResponse) GetSignature() []byte {
	if x, ok := x.GetMsg().(*SignTransactionResponse_Signature); ok {
		return x.Signature
	}
	return nil
}

type isSignTransactionResponse_Msg interface {
	isSignTransactionResponse_Msg()
}

type SignTransactionResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type SignTransactionResponse_Signature struct {
	// The signature of the transaction.
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3,oneof"`
}

func (*SignTransactionResponse_Rejected) isSignTransactionResponse_Msg() {}

func (*SignTransactionResponse_Signature) isSignTransactionResponse_Msg() {}

var File_perun_wallet_proto protoreflect.FileDescriptor

var file_perun_wallet_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x2d, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x1a, 0x0a, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x08, 0x52,
	0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22,
	0x56, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x06, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x65, 0x72, 0x75,
	0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52,
	0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x22, 0x73, 0x0a, 0x13, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34,
	0x0a, 0x08, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x49, 0x64, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x5d, 0x0a, 0x14,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x77, 0x69, 0x72, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x59, 0x0a, 0x10, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x26, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x8e, 0x01, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x34, 0x0a, 0x08, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65,
	0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x38, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x34, 0x0a, 0x13, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x30, 0x0a,
	0x0f, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22,
	0x8a, 0x01, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x72, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x65, 0x72,
	0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x35,
	0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05,
	0x63, 0x6c, 0x6f, 0x73, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x39, 0x0a, 0x18,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x14, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x66, 0x75, 0x6c, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x8f,
	0x01, 0x0a, 0x19, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x08,
	0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65,
	0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x12, 0x35, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x60, 0x0a, 0x17, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x65, 0x72, 0x75,
	0x6e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x22, 0x91, 0x01, 0x0a, 0x18, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x34, 0x0a, 0x08, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x6a,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x38, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42,
	0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x5b, 0x0a, 0x12, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x65,
	0x72, 0x75, 0x6e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x49, 0x64, 0x22, 0x5c, 0x0a, 0x13, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e,
	0x77, 0x69, 0x72, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x22, 0x61, 0x0a, 0x18, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x65,
	0x72, 0x75, 0x6e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x22, 0x5e, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x65,
	0x72, 0x75, 0x6e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x22, 0x62, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x65, 0x64, 0x22, 0x28, 0x0a, 0x12, 0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x72, 0x0a, 0x13,
	0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52,
	0x08, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x3f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x77, 0x69, 0x72, 0x65,
	0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x22, 0x40, 0x0a, 0x05, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x22, 0x35, 0x0a, 0x06, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x2b, 0x0a,
	0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x52, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x22, 0x50, 0x0a, 0x19, 0x55, 0x6e,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x5f, 0x69, 0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x49, 0x64, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x91, 0x01, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x45, 0x0a, 0x08, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x55, 0x6e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x08, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x65, 0x72, 0x75,
	0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x48,
	0x00, 0x52, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x3a, 0x0a, 0x16, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x76, 0x0a, 0x17,
	0x53, 0x69, 0x67, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x72, 0x65, 0x6a, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x65, 0x72, 0x75,
	0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x1e, 0x0a,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x05, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x32, 0xde, 0x03, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x6e, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x20, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4f, 0x70, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4f,
	0x70, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0d, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x22, 0x2e, 0x70,
	0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x21, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x11,
	0x46, 0x6f, 0x72, 0x63, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x12, 0x26, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x43, 0x6c, 0x6f,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x70, 0x65, 0x72, 0x75,
	0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x46, 0x6f, 0x72, 0x63, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x61, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x25, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61,
	0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb2, 0x05, 0x0a, 0x0d, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x6e, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x20, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x49, 0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x21, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x53, 0x0a, 0x11, 0x46,
	0x6f, 0x72, 0x63, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x26, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x46, 0x6f, 0x72, 0x63, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x4d, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x23, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x67, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28,
	0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x65, 0x72, 0x75,
	0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x0f,
	0x53, 0x69, 0x67, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x24, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x69, 0x67, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x65, 0x72, 0x75, 0x6e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x1e, 0x2e, 0x70, 0x65, 0x72, 0x75,
	0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x65, 0x72, 0x75,
	0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_perun_wallet_proto_rawDescOnce sync.Once
	file_perun_wallet_proto_rawDescData = file_perun_wallet_proto_rawDesc
)

func file_perun_wallet_proto_rawDescGZIP() []byte {
	file_perun_wallet_proto_rawDescOnce.Do(func() {
		file_perun_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(file_perun_wallet_proto_rawDescData)
	})
	return file_perun_wallet_proto_rawDescData
}

var file_perun_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_perun_wallet_proto_goTypes = []interface{}{
	(*Rejected)(nil),                   // 0: perunservice.Rejected
	(*ChannelOpenRequest)(nil),         // 1: perunservice.ChannelOpenRequest
	(*ChannelOpenResponse)(nil),        // 2: perunservice.ChannelOpenResponse
	(*ChannelUpdateRequest)(nil),       // 3: perunservice.ChannelUpdateRequest
	(*SuccessfulUpdate)(nil),           // 4: perunservice.SuccessfulUpdate
	(*ChannelUpdateResponse)(nil),      // 5: perunservice.ChannelUpdateResponse
	(*ChannelCloseRequest)(nil),        // 6: perunservice.ChannelCloseRequest
	(*SuccessfulClose)(nil),            // 7: perunservice.SuccessfulClose
	(*ChannelCloseResponse)(nil),       // 8: perunservice.ChannelCloseResponse
	(*ChannelForceCloseRequest)(nil),   // 9: perunservice.ChannelForceCloseRequest
	(*SuccessfulForceClose)(nil),       // 10: perunservice.SuccessfulForceClose
	(*ChannelForceCloseResponse)(nil),  // 11: perunservice.ChannelForceCloseResponse
	(*ChallengeChannelRequest)(nil),    // 12: perunservice.ChallengeChannelRequest
	(*ChallengeChannelResponse)(nil),   // 13: perunservice.ChallengeChannelResponse
	(*OpenChannelRequest)(nil),         // 14: perunservice.OpenChannelRequest
	(*CloseChannelRequest)(nil),        // 15: perunservice.CloseChannelRequest
	(*ForceCloseChannelRequest)(nil),   // 16: perunservice.ForceCloseChannelRequest
	(*ChallengeEventRequest)(nil),      // 17: perunservice.ChallengeEventRequest
	(*UpdateNotificationRequest)(nil),  // 18: perunservice.UpdateNotificationRequest
	(*UpdateNotificationResponse)(nil), // 19: perunservice.UpdateNotificationResponse
	(*SignMessageRequest)(nil),         // 20: perunservice.SignMessageRequest
	(*SignMessageResponse)(nil),        // 21: perunservice.SignMessageResponse
	(*GetAssetsRequest)(nil),           // 22: perunservice.GetAssetsRequest
	(*Asset)(nil),                      // 23: perunservice.Asset
	(*Assets)(nil),                     // 24: perunservice.Assets
	(*UnmatchableAssetsResponse)(nil),  // 25: perunservice.UnmatchableAssetsResponse
	(*GetAssetsResponse)(nil),          // 26: perunservice.GetAssetsResponse
	(*SignTransactionRequest)(nil),     // 27: perunservice.SignTransactionRequest
	(*SignTransactionResponse)(nil),    // 28: perunservice.SignTransactionResponse
	(*protobuf.State)(nil),             // 29: perunwire.State
	(*protobuf.Balances)(nil),          // 30: perunwire.Balances
	(*emptypb.Empty)(nil),              // 31: google.protobuf.Empty
}
var file_perun_wallet_proto_depIdxs = []int32{
	24, // 0: perunservice.ChannelOpenRequest.assets:type_name -> perunservice.Assets
	0,  // 1: perunservice.ChannelOpenResponse.rejected:type_name -> perunservice.Rejected
	29, // 2: perunservice.ChannelUpdateRequest.state:type_name -> perunwire.State
	29, // 3: perunservice.SuccessfulUpdate.state:type_name -> perunwire.State
	0,  // 4: perunservice.ChannelUpdateResponse.rejected:type_name -> perunservice.Rejected
	4,  // 5: perunservice.ChannelUpdateResponse.update:type_name -> perunservice.SuccessfulUpdate
	0,  // 6: perunservice.ChannelCloseResponse.rejected:type_name -> perunservice.Rejected
	7,  // 7: perunservice.ChannelCloseResponse.close:type_name -> perunservice.SuccessfulClose
	0,  // 8: perunservice.ChannelForceCloseResponse.rejected:type_name -> perunservice.Rejected
	7,  // 9: perunservice.ChannelForceCloseResponse.close:type_name -> perunservice.SuccessfulClose
	29, // 10: perunservice.ChallengeChannelRequest.state:type_name -> perunwire.State
	0,  // 11: perunservice.ChallengeChannelResponse.rejected:type_name -> perunservice.Rejected
	4,  // 12: perunservice.ChallengeChannelResponse.update:type_name -> perunservice.SuccessfulUpdate
	29, // 13: perunservice.OpenChannelRequest.state:type_name -> perunwire.State
	29, // 14: perunservice.CloseChannelRequest.state:type_name -> perunwire.State
	29, // 15: perunservice.ForceCloseChannelRequest.state:type_name -> perunwire.State
	29, // 16: perunservice.ChallengeEventRequest.state:type_name -> perunwire.State
	29, // 17: perunservice.UpdateNotificationRequest.state:type_name -> perunwire.State
	0,  // 18: perunservice.SignMessageResponse.rejected:type_name -> perunservice.Rejected
	30, // 19: perunservice.GetAssetsRequest.assets:type_name -> perunwire.Balances
	23, // 20: perunservice.Assets.assets:type_name -> perunservice.Asset
	25, // 21: perunservice.GetAssetsResponse.rejected:type_name -> perunservice.UnmatchableAssetsResponse
	24, // 22: perunservice.GetAssetsResponse.assets:type_name -> perunservice.Assets
	0,  // 23: perunservice.SignTransactionResponse.rejected:type_name -> perunservice.Rejected
	1,  // 24: perunservice.ChannelService.OpenChannel:input_type -> perunservice.ChannelOpenRequest
	3,  // 25: perunservice.ChannelService.UpdateChannel:input_type -> perunservice.ChannelUpdateRequest
	6,  // 26: perunservice.ChannelService.CloseChannel:input_type -> perunservice.ChannelCloseRequest
	9,  // 27: perunservice.ChannelService.ForceCloseChannel:input_type -> perunservice.ChannelForceCloseRequest
	12, // 28: perunservice.ChannelService.ChallengeChannel:input_type -> perunservice.ChallengeChannelRequest
	14, // 29: perunservice.WalletService.OpenChannel:input_type -> perunservice.OpenChannelRequest
	15, // 30: perunservice.WalletService.CloseChannel:input_type -> perunservice.CloseChannelRequest
	16, // 31: perunservice.WalletService.ForceCloseChannel:input_type -> perunservice.ForceCloseChannelRequest
	17, // 32: perunservice.WalletService.ChallengeEvent:input_type -> perunservice.ChallengeEventRequest
	18, // 33: perunservice.WalletService.UpdateNotification:input_type -> perunservice.UpdateNotificationRequest
	20, // 34: perunservice.WalletService.SignMessage:input_type -> perunservice.SignMessageRequest
	27, // 35: perunservice.WalletService.SignTransaction:input_type -> perunservice.SignTransactionRequest
	22, // 36: perunservice.WalletService.GetAssets:input_type -> perunservice.GetAssetsRequest
	2,  // 37: perunservice.ChannelService.OpenChannel:output_type -> perunservice.ChannelOpenResponse
	5,  // 38: perunservice.ChannelService.UpdateChannel:output_type -> perunservice.ChannelUpdateResponse
	8,  // 39: perunservice.ChannelService.CloseChannel:output_type -> perunservice.ChannelCloseResponse
	11, // 40: perunservice.ChannelService.ForceCloseChannel:output_type -> perunservice.ChannelForceCloseResponse
	13, // 41: perunservice.ChannelService.ChallengeChannel:output_type -> perunservice.ChallengeChannelResponse
	31, // 42: perunservice.WalletService.OpenChannel:output_type -> google.protobuf.Empty
	31, // 43: perunservice.WalletService.CloseChannel:output_type -> google.protobuf.Empty
	31, // 44: perunservice.WalletService.ForceCloseChannel:output_type -> google.protobuf.Empty
	31, // 45: perunservice.WalletService.ChallengeEvent:output_type -> google.protobuf.Empty
	19, // 46: perunservice.WalletService.UpdateNotification:output_type -> perunservice.UpdateNotificationResponse
	21, // 47: perunservice.WalletService.SignMessage:output_type -> perunservice.SignMessageResponse
	28, // 48: perunservice.WalletService.SignTransaction:output_type -> perunservice.SignTransactionResponse
	26, // 49: perunservice.WalletService.GetAssets:output_type -> perunservice.GetAssetsResponse
	37, // [37:50] is the sub-list for method output_type
	24, // [24:37] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_perun_wallet_proto_init() }
func file_perun_wallet_proto_init() {
	if File_perun_wallet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_perun_wallet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rejected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelOpenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelOpenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessfulUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelCloseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessfulClose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelCloseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelForceCloseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessfulForceClose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelForceCloseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChallengeChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChallengeChannelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForceCloseChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChallengeEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNotificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Asset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Assets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnmatchableAssetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignTransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perun_wallet_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignTransactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_perun_wallet_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ChannelOpenResponse_Rejected)(nil),
		(*ChannelOpenResponse_ChannelId)(nil),
	}
	file_perun_wallet_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*ChannelUpdateResponse_Rejected)(nil),
		(*ChannelUpdateResponse_Update)(nil),
	}
	file_perun_wallet_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*ChannelCloseResponse_Rejected)(nil),
		(*ChannelCloseResponse_Close)(nil),
	}
	file_perun_wallet_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*ChannelForceCloseResponse_Rejected)(nil),
		(*ChannelForceCloseResponse_Close)(nil),
	}
	file_perun_wallet_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*ChallengeChannelResponse_Rejected)(nil),
		(*ChallengeChannelResponse_Update)(nil),
	}
	file_perun_wallet_proto_msgTypes[21].OneofWrappers = []interface{}{
		(*SignMessageResponse_Rejected)(nil),
		(*SignMessageResponse_Signature)(nil),
	}
	file_perun_wallet_proto_msgTypes[26].OneofWrappers = []interface{}{
		(*GetAssetsResponse_Rejected)(nil),
		(*GetAssetsResponse_Assets)(nil),
	}
	file_perun_wallet_proto_msgTypes[28].OneofWrappers = []interface{}{
		(*SignTransactionResponse_Rejected)(nil),
		(*SignTransactionResponse_Signature)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_perun_wallet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_perun_wallet_proto_goTypes,
		DependencyIndexes: file_perun_wallet_proto_depIdxs,
		MessageInfos:      file_perun_wallet_proto_msgTypes,
	}.Build()
	File_perun_wallet_proto = out.File
	file_perun_wallet_proto_rawDesc = nil
	file_perun_wallet_proto_goTypes = nil
	file_perun_wallet_proto_depIdxs = nil
}
